### ISSUE TITLE
Failed at the gatsby-starter-stripe@0.1.0 develop script

### ISSUE THREAD

**Issue by brettbartylla** [brxck/gatsby-starter-stripe#1] opened 2019-04-23 00:02 UTC
I Created a new project using this starter and Configured my API Keys with no issues. However, I get the following errors after I run "npm run start" 

![Screen Shot 2019-04-22 at 7 12 43 PM](https://user-images.githubusercontent.com/12302037/56541941-b7ec5600-6532-11e9-8369-45727aad252e.png)

![Screen Shot 2019-04-22 at 7 01 18 PM](https://user-images.githubusercontent.com/12302037/56541324-0c8ed180-6531-11e9-97de-c5b81c4f85c6.png)
Here is the log:
[2019-04-22T23_18_17_599Z-debug.log](https://github.com/brxck/gatsby-starter-stripe/files/3105261/2019-04-22T23_18_17_599Z-debug.log)

Any ideas as to what might be going wrong here?

**Comment by brxck** [comment] 2019-04-24 20:24
In my experience this means gatsby-source-stripe wasn't able to create any Sku nodes, so there's nothing to query. Have you created skus in your Stripe account?

**Comment by brettbartylla** [comment] 2019-05-05 20:10
I have created one product with three skus:
![Screen Shot 2019-05-05 at 3 09 02 PM](https://user-images.githubusercontent.com/12302037/57199722-d0ec0280-6f47-11e9-9f5b-6b85a27f0df0.png)

**Comment by stcalica** [comment] 2019-08-08 23:06
Slowly chipping away at this.

First, I had an issue with not recognizing images. 
So you need to include images in the overall products and information there and then add that image to the SKUs, for some reason placing a URL does not work there.

Now I have this issue: 

<img width="1139" alt="Screen Shot 2019-08-08 at 4 03 34 PM" src="https://user-images.githubusercontent.com/5624835/62743170-3bed1f80-b9f6-11e9-9ce6-ddf3f7e5df07.png">


However, I added a price to my SKUs. 

_**I think the issue is we need more documentation on how to set this up in Stripe so the queries work. Secondly, maybe making the queries more grateful for those who don't have all the requirements for some reason?**_

**Comment by brxck** [comment] 2019-08-10 17:59
@stcalica the issue in the image you provided is that the result of `sku[id]` is undefined, not that `price` is undefined. I don't have enough info to say why that is.

> Secondly, maybe making the queries more grateful for those who don't have all the requirements for some reason?

As far as this goes, the graphQL queries are pretty all or nothing. They will throw an error if the field does not exist, and I don't know of a way around that.

**Comment by stcalica** [comment] 2019-08-12 16:11
@brxck yeah GatsbyJS is my first run in with GraphQL. So are you saying GraphQL doesn't state what's missing? Just a fail or not? 
That's really annoying for a project like this. 
Then again I need to run my own checks, but was just trying to use this right of the box.

**Comment by brxck** [comment] 2019-08-31 21:55
I believe any issues should be fixed by the new gatsby-source-stripe version, and required fields are now clarified in the README thanks to #12.

**Closed as completed by brxck** 2019-08-31 21:55 UTC
